#ifndef CMDSTRINGLIST_H_INCLUDED
#define CMDSTRINGLIST_H_INCLUDED

#define COMMAND_BACK_SUCCESS    "COMMAND=BACK=SUCCESS"
#define COMMAND_BACK_FAILED     "COMMAND=BACK=FAILED="
#define COMMAND_LIST_BEGIN      "COMMAND=LIST=BEGIN=="
#define COMMAND_LIST_END        "COMMAND=LIST=END===="
#define COMMAND_KICK_NOTFOUND   "COMMAND=KCIK=NOFOUND"
#define COMMAND_SEND_NOTFOUND   "COMMAND=SEND=NOFOUND"

#define COMMAND_LOGIN           "COMMAND=REGISTER=ME="
#define COMMAND_LOGOUT          "COMMAND=DELETE=ME==="
#define COMMAND_CONFIRM_TYPE    "COMMAND=COMFIRM=TYPE"
#define COMMAND_RETURN_TYPE     "COMMAND=RETURN=TYPE="
#define COMMAND_HELPSEND_TO     "COMMAND=HELPSEND=TO="


#endif // CMDSTRINGLIST_H_INCLUDED
