#ifndef DEFVARS_H_INCLUDED
#define DEFVARS_H_INCLUDED



#endif // DEFVARS_H_INCLUDED

#define SOCKADDR_IN struct sockaddr_in

#define COMMAND_BACK_SUCCESS    "COMMAND=BACK=SUCCESS"
#define COMMAND_BACK_FAILED     "COMMAND=BACK=FAILED="
#define COMMAND_LIST_BEGIN      "COMMAND=LIST=BEGIN=="
#define COMMAND_LIST_END        "COMMAND=LIST=END===="
#define COMMAND_LIST_DATA		"COMMAND=LIST=DATA==="
#define COMMAND_LIST_EMPTY		"COMMAND=LIST=EMPTY=="
#define COMMAND_KICK_NOTFOUND   "COMMAND=KCIK=NOFOUND"
#define COMMAND_SEND_NOTFOUND   "COMMAND=SEND=NOFOUND"
#define COMMAND_SERVER_BUSY		"COMMAND=SERVER=BUSY="

#define COMMAND_LOGIN           "COMMAND=REGISTER=ME="
#define COMMAND_LOGOUT          "COMMAND=DELETE=ME==="
#define COMMAND_CONFIRM_TYPE    "COMMAND=COMFIRM=TYPE"
#define COMMAND_READY           "COMMAND=BEGIN=ACTION"
#define COMMAND_RETURN_TYPE     "COMMAND=RETURN=TYPE="
#define COMMAND_HELPSEND_TO     "COMMAND=HELPSEND=TO="
#define COMMAND_GET_CLIENTS     "COMMAND=GET=ONLINES="
#define COMMAND_TRANSLATE       "COMMAND=TRANSLATE==="

#define HD_LOGIN_ERROR			1000
#define HD_LOGIN_SUCCESS		1001


#define PORT_CMD 	9880
#define PORT_SER 	9881
#define PORT_NAT 	9882
#define PORT_LST	9883

#define MAXDATA 	1024
#define MAXCMD 		128
